# Generated by Django 2.1.2 on 2018-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
